[package]
name = "telegrand"
version = "0.1.0"
authors = ["Marco Melorio <marco.melorio@protonmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.2.0-alpha.2", package = "libadwaita", features = ["v1_2"] }
anyhow = "1.0"
futures = { version = "0.3", default-features = false }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.4", package = "gtk4", features = ["v4_6"] }
image = { version = "0.24", default-features = false, features = ["webp"] }
indexmap = "1.9"
locale_config = "0.3"
log = "0.4"
once_cell = "1.13"
pretty_env_logger = "0.4"
qrcode-generator = { version = "4.1", default-features = false }
regex = "1.6"
shumate = { version = "0.1.0-alpha.4", package = "libshumate" }
tdlib = { version = "0.1", default-features = false }
temp-dir = "0.1"
thiserror = "1.0"
