[package]
name = "telegrand"
version = "0.1.0"
authors = ["Marco Melorio <marco.melorio@protonmail.com>"]
edition = "2018"

[dependencies]
adw = { version = "0.1.0-alpha-6", package = "libadwaita" }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.3", package = "gtk4" }
indexmap = "1.7"
locale_config = "0.3"
log = "0.4"
once_cell = "1.8"
pretty_env_logger = "0.4"
qrcode-generator = { version = "4.1", default-features = false }
regex = "1.5"
tdgrand = { git = "https://github.com/melix99/tdgrand", branch = "main" }
tokio = { version = "1", features = ["rt-multi-thread"] }
