name: CI

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:

jobs:
  check-commit-style:
    name: Check Commit Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.1.0

  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master
        with:
          config: ./.github/workflows/typos.toml

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run cargo fmt
        run: cargo +nightly fmt --all -- --check

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      # Docker is required by the docker/setup-qemu-action which enables emulation
      - name: Install dependencies
        if: ${{ matrix.arch != 'x86_64' }}
        run: dnf -y install docker
      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v5
        with:
          bundle: paper-plane.flatpak
          manifest-path: build-aux/app.drey.PaperPlane.Devel.json
          arch: ${{ matrix.arch }}
          cache-key: flatpak-builder-${{ github.sha }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Release
    runs-on: ubuntu-latest
    needs: [flatpak]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create vendored sources
        run: build-aux/dist-vendor.sh ../ src
        shell: bash
      - name: Archive repository
        run: git archive --format tar HEAD > paper-plane-${{ github.ref_name }}.tar
      - name: Add vendored sources and cargo config to tarball
        run: tar -rf paper-plane-${{ github.ref_name }}.tar .cargo vendor
      - name: Compress tarball
        run: xz -z paper-plane-${{ github.ref_name }}.tar
      - name: Generate checksum
        run: sha256sum paper-plane-${{ github.ref_name }}.tar.xz > paper-plane-${{ github.ref_name }}.tar.xz.sha256sum
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - name: Extract release notes
        run: |
          echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
          xmllint --xpath '//release[1]/description' data/app.drey.PaperPlane.metainfo.xml.in.in | xmllint --format - >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body: ${{ env.RELEASE_NOTES }}
          prerelease: ${{ contains(github.ref, 'beta') }}
          files: |
            paper-plane-${{ github.ref_name }}.tar.xz
            paper-plane-${{ github.ref_name }}.tar.xz.sha256sum
