name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run cargo fmt
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Build dependencies
        run: |
          flatpak-builder \
          --disable-rofiles-fuse \
          --install-deps-from=flathub \
          --keep-build-dirs \
          --stop-at=telegrand \
          flatpak_app build-aux/com.github.melix99.telegrand.Devel.json
      - name: Run clippy
        run: |
          echo "cargo clippy -- -D warnings" \
          | flatpak-builder \
          --disable-rofiles-fuse \
          --build-shell=telegrand \
          flatpak_app build-aux/com.github.melix99.telegrand.Devel.json

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    needs: [rustfmt, clippy]
    steps:
      - uses: actions/checkout@v2
      # Docker is required by the docker/setup-qemu-action which enables emulation
      - name: Install dependencies
        if: ${{ matrix.arch != 'x86_64' }}
        run: dnf -y install docker
      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: telegrand.flatpak
          manifest-path: build-aux/com.github.melix99.telegrand.Devel.json
          run-tests: true
          arch: ${{ matrix.arch }}
          # TODO: Currently there is bug where, roughly speaking, there is an error in the creation of the cache.
          #       Consider this for removal as soon as flatpak-builder@v5 is released, which is supposed to fix it.
          cache-key: flatpak-builder-${{ github.sha }}
