name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master
        with:
          config: ./.github/workflows/typos.toml

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run cargo fmt
        run: cargo +nightly fmt --all -- --check

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      # Docker is required by the docker/setup-qemu-action which enables emulation
      - name: Install dependencies
        if: ${{ matrix.arch != 'x86_64' }}
        run: dnf -y install docker
      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v5
        with:
          bundle: telegrand.flatpak
          manifest-path: build-aux/com.github.melix99.telegrand.Devel.json
          arch: ${{ matrix.arch }}
          cache-key: flatpak-builder-${{ github.sha }}
